/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import action.DepartmentAction;
import action.TeacherAction;
import infobean.TeacherInfoBean;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author reqaw
 */
public class AddTeacherFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddTeacherFrame
     */
    public AddTeacherFrame() {
        initComponents();
        int windowWidth = this.getWidth(); //获得窗口宽

        int windowHeight = this.getHeight(); //获得窗口高

        Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包

        Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸

        int screenWidth = screenSize.width; //获取屏幕的宽

        int screenHeight = screenSize.height; //获取屏幕的高

        this.setLocation(screenWidth / 2 - windowWidth / 2, screenHeight / 2 - windowHeight / 2);//设置窗口居中显示
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherIDL = new javax.swing.JLabel();
        teacherIDT = new javax.swing.JTextField();
        teacherNameL = new javax.swing.JLabel();
        teacherNameT = new javax.swing.JTextField();
        teacherBirthL = new javax.swing.JLabel();
        teacherBirthT = new javax.swing.JTextField();
        teacherSexL = new javax.swing.JLabel();
        teacherSchoolL = new javax.swing.JLabel();
        teacherSchoolT = new javax.swing.JTextField();
        teacherTechL = new javax.swing.JLabel();
        teacherTechT = new javax.swing.JTextField();
        teacherAddressL = new javax.swing.JLabel();
        teacherAddressT = new javax.swing.JTextField();
        teacherIndateL = new javax.swing.JLabel();
        teacherIndateT = new javax.swing.JTextField();
        teacherDepartL = new javax.swing.JLabel();
        teacherDepartComboBox = new javax.swing.JComboBox<>();
        teacherDutyL = new javax.swing.JLabel();
        teacherDutyT = new javax.swing.JTextField();
        addTeacherB = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        teacherSexComboBox = new javax.swing.JComboBox<>();
        resetB = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        teacherIDL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherIDL.setText("员工编号：");

        teacherIDT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherNameL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherNameL.setText("姓名：");

        teacherNameT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherBirthL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherBirthL.setText("出生日期：");

        teacherBirthT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherSexL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherSexL.setText("性别：");

        teacherSchoolL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherSchoolL.setText("毕业院校：");

        teacherSchoolT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherTechL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherTechL.setText("专业：");

        teacherTechT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherAddressL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherAddressL.setText("家庭地址：");

        teacherAddressT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherIndateL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherIndateL.setText("入职时间：");

        teacherIndateT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        teacherDepartL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherDepartL.setText("部门：");

        teacherDepartComboBox.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherDepartComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "党委办公室", "组织部", "宣传部", "统战部", "纪委办公室", "校长办公室", "发展规划处", "教务处", "科研处", "学生处", "研究生处", "招生就业处", "人事处", "财务处", "国际交流处", "基建处", "财产管理处", "后勤处", "监察处", "审计处", "离退处", "保卫处", "网络中心", "图书馆", "校工会", "校团委", "发展规划处" }));
        teacherDepartComboBox.setSelectedIndex(-1);

        teacherDutyL.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherDutyL.setText("岗位：");

        teacherDutyT.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        addTeacherB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        addTeacherB.setText("添加");
        addTeacherB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherBActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel11.setText("格式：1976-10-10");

        teacherSexComboBox.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        teacherSexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "男", "女" }));

        resetB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        resetB.setText("重置");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel12.setText("格式：1976-10-10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherDepartL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teacherDepartComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherAddressL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teacherAddressT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherTechL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teacherTechT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherSchoolL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teacherSchoolT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherSexL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teacherSexComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teacherNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherBirthL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(teacherBirthT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(teacherIndateL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(teacherIndateT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teacherDutyL, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(resetB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(addTeacherB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(teacherDutyT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teacherIDL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teacherIDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherIDL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherNameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherBirthL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherBirthT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherSexL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherSchoolL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherSchoolT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherTechL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherTechT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherAddressL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherAddressT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherIndateL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherIndateT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherDepartL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDepartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherDutyL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDutyT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTeacherB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTeacherBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherBActionPerformed
        if(this.teacherIDT.getText().trim().equals("") || this.teacherNameT.getText().trim().equals("") || this.teacherBirthT.getText().trim().equals("")
                || this.teacherSchoolT.getText().trim().equals("") || this.teacherTechT.getText().trim().equals("") || this.teacherAddressT.getText().trim().equals("")
                || this.teacherIndateT.getText().trim().equals("") || ((String)this.teacherDepartComboBox.getSelectedItem()).equals("") || this.teacherDutyT.getText().trim().equals("")) {
 
            JOptionPane.showMessageDialog(null, "<html><font Color='red'>请输入将员工信息填写完整再添加" ,"错误", JOptionPane.ERROR_MESSAGE);
        }
        TeacherInfoBean teacherinfo = new TeacherInfoBean();
        teacherinfo.setTeacherId(this.teacherIDT.getText().trim());
        teacherinfo.setTeacherName(this.teacherNameT.getText().trim());
        teacherinfo.setTeacherBirthday(this.teacherBirthT.getText().trim());
        teacherinfo.setTeacherSex((String)this.teacherSexComboBox.getSelectedItem());
        teacherinfo.setTeacherSchool(this.teacherSchoolT.getText().trim());
        teacherinfo.setTeacherTech(this.teacherTechT.getText().trim());
        teacherinfo.setTeacherAddress(this.teacherAddressT.getText().trim());
        teacherinfo.setTeacherIndate(this.teacherIndateT.getText().trim());
        DepartmentAction departmentAction = new DepartmentAction();
        teacherinfo.setTeacherDepartment(departmentAction.findDepartmentIDByDepartmentName((String)this.teacherDepartComboBox.getSelectedItem()));
        teacherinfo.setTeacherDuty(this.teacherDutyT.getText().trim());
       
        TeacherAction teacherAction = new TeacherAction();
        if(teacherAction.findTeacherByTeacherID(teacherinfo.getTeacherId()) != null) {
            JOptionPane.showMessageDialog(null, "<html><font Color='red'>该员工编号已存在,请重新输入" ,"错误", JOptionPane.ERROR_MESSAGE);
            this.teacherIDT.setText("");
        } else {
            int ok = teacherAction.addTeacher(teacherinfo);
            if(ok < 0)
                JOptionPane.showMessageDialog(null, "<html><font Color='red'>添加员工失败","错误", JOptionPane.ERROR_MESSAGE);
            else {
                JOptionPane.showMessageDialog(null, "<html><font Color='red'>添加员工成功！", "提示", JOptionPane.INFORMATION_MESSAGE);
                this.teacherIDT.setText("");
                this.teacherNameT.setText("");
                this.teacherBirthT.setText("");
                this.teacherSchoolT.setText("");
                this.teacherTechT.setText("");
                this.teacherSexComboBox.setSelectedIndex(0);
                this.teacherAddressT.setText("");
                this.teacherIndateT.setText("");
                this.teacherDutyT.setText("");
                this.teacherDepartComboBox.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_addTeacherBActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        this.teacherIDT.setText("");
        this.teacherNameT.setText("");
        this.teacherBirthT.setText("");
        this.teacherSchoolT.setText("");
        this.teacherTechT.setText("");
        this.teacherAddressT.setText("");
        this.teacherIndateT.setText("");
        this.teacherDutyT.setText("");
        this.teacherDepartComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_resetBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeacherFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeacherB;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JButton resetB;
    private javax.swing.JLabel teacherAddressL;
    private javax.swing.JTextField teacherAddressT;
    private javax.swing.JLabel teacherBirthL;
    private javax.swing.JTextField teacherBirthT;
    private javax.swing.JComboBox<String> teacherDepartComboBox;
    private javax.swing.JLabel teacherDepartL;
    private javax.swing.JLabel teacherDutyL;
    private javax.swing.JTextField teacherDutyT;
    private javax.swing.JLabel teacherIDL;
    private javax.swing.JTextField teacherIDT;
    private javax.swing.JLabel teacherIndateL;
    private javax.swing.JTextField teacherIndateT;
    private javax.swing.JLabel teacherNameL;
    private javax.swing.JTextField teacherNameT;
    private javax.swing.JLabel teacherSchoolL;
    private javax.swing.JTextField teacherSchoolT;
    private javax.swing.JComboBox<String> teacherSexComboBox;
    private javax.swing.JLabel teacherSexL;
    private javax.swing.JLabel teacherTechL;
    private javax.swing.JTextField teacherTechT;
    // End of variables declaration//GEN-END:variables
}
