/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.User;
import dao.UserDAOImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author reqaw
 */
public class UserRegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserRegisterFrame
     */
    public UserRegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserPwdL = new javax.swing.JLabel();
        UserIdL1 = new javax.swing.JLabel();
        UserPwdL2 = new javax.swing.JLabel();
        UserIdT = new javax.swing.JTextField();
        UserPwdT = new javax.swing.JTextField();
        UserPwdT2 = new javax.swing.JTextField();
        ResetB = new javax.swing.JButton();
        UserRegisterB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        UserPwdL.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        UserPwdL.setText("密码：");

        UserIdL1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        UserIdL1.setText("账户：");

        UserPwdL2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        UserPwdL2.setText("确认密码：");

        UserIdT.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        UserPwdT.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        UserPwdT2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        ResetB.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        ResetB.setText("重置");
        ResetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBActionPerformed(evt);
            }
        });

        UserRegisterB.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        UserRegisterB.setText("注册");
        UserRegisterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegisterBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResetB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserRegisterB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserPwdL2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserPwdL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserIdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserIdT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserPwdT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserPwdT2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIdT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserPwdL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserPwdT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserPwdL2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserPwdT2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResetB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserRegisterB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBActionPerformed
        this.UserIdT.setText("");
        this.UserPwdT.setText("");
        this.UserPwdT2.setText("");
    }//GEN-LAST:event_ResetBActionPerformed

    private void UserRegisterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegisterBActionPerformed
        String userId = this.UserIdT.getText().trim();
        UserDAOImpl userDao = new UserDAOImpl();
        String pwd1 = this.UserPwdT.getText().trim();
        String pwd2 = this.UserPwdT2.getText().trim();
        if(userId.equals("")) {
             JOptionPane.showMessageDialog(null, "<html><font Color='red'>账户不能为空，请输入" ,"错误", JOptionPane.WARNING_MESSAGE);
             this.UserIdT.setText("");
        } else if(userDao.findUserByUserId(this.UserIdT.getText().trim())){
             JOptionPane.showMessageDialog(null, "<html><font Color='red'>此账户已存在，请重新输入" ,"错误", JOptionPane.WARNING_MESSAGE);
             this.UserIdT.setText("");
        } else if(!pwd1.equals(pwd2)){
            JOptionPane.showMessageDialog(null, "<html><font Color='red'>输入的两次密码不一致，请重新输入" ,"错误", JOptionPane.ERROR_MESSAGE);
            this.UserPwdT.setText("");
            this.UserPwdT2.setText("");
        } else {
            User user = new User();
            user.setUserID(userId);
            user.setUserPWD(pwd1);
            if(userDao.Register(user) > 0) {
                JOptionPane.showMessageDialog(null, "<html><font Color='red'>注册成功" ,"提示", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "<html><font Color='red'>注册失败,请重新注册" ,"错误", JOptionPane.ERROR_MESSAGE);
            }
        }       
    }//GEN-LAST:event_UserRegisterBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetB;
    private javax.swing.JLabel UserIdL1;
    private javax.swing.JTextField UserIdT;
    private javax.swing.JLabel UserPwdL;
    private javax.swing.JLabel UserPwdL2;
    private javax.swing.JTextField UserPwdT;
    private javax.swing.JTextField UserPwdT2;
    private javax.swing.JButton UserRegisterB;
    // End of variables declaration//GEN-END:variables
}
